image: registry.gitlab.com/new-age-tech/gitlab-ci-runner-docker/gitlab-ci-runner-docker:latest

services:
- docker:dind

stages:
- build

build_and_push:
  stage: build
  only:
  - master
  variables:
    REGISTRY_FULL_PATH: "${CI_REGISTRY_IMAGE}"
    IMAGE_TAG: "${CI_COMMIT_SHA}"
  before_script:
  - print_info
  - docker login --username "${CI_DEPLOY_USER}" --password "${CI_DEPLOY_PASSWORD}" "${CI_REGISTRY}"
  script:
  # TODO: fix caching
  - IMAGE_TAG=latest docker-compose --file ./base.yml --file ./build.yml --file ./production.yml pull
  - docker-compose --file ./base.yml --file ./build.yml --file ./production.yml build
  - docker-compose --file ./base.yml --file ./build.yml --file ./production.yml push
  - IMAGE_TAG=latest docker-compose --file ./base.yml --file ./build.yml --file ./production.yml build
  - IMAGE_TAG=latest docker-compose --file ./base.yml --file ./build.yml --file ./production.yml push
  after_script:
  - docker logout "${CI_REGISTRY}"
