version: '3.6'

volumes:
  grafana_data: {}
  prometheus_data: {}

networks:
  backend:

services:
  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    restart: always
    networks:
    - backend
    depends_on:
    - prometheus
    volumes:
    - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.9.2
    container_name: prometheus
    restart: always
    depends_on:
    - cadvisor
    networks:
    - backend
    volumes:
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: always
    networks:
    - backend
    volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /var/run:/var/run:rw
    - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:v0.18.0
    container_name: node-exporter
    restart: always
    networks:
    - backend
    volumes:
    - /:/rootfs:ro
    - /sys:/host/sys:ro
    - /proc:/host/proc:ro
    command:
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - --collector.filesystem.ignored-mount-points
    - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  alertmanager:
    image: prom/alertmanager:v0.17.0
    container_name: alertmanager
    restart: always
    networks:
    - backend
    command:
    - '--config.file=/etc/alertmanager/config.yml'
    - '--storage.path=/alertmanager'
