version: '3.6'

services:
  grafana:
    build:
      context: ./docker/grafana/
      cache_from:
        - ${REGISTRY_FULL_PATH}/grafana:latest

  prometheus:
    build:
      context: ./docker/prometheus/
      cache_from:
        - ${REGISTRY_FULL_PATH}/prometheus:latest

  cadvisor:
    build:
      context: ./docker/cadvisor/
      cache_from:
        - ${REGISTRY_FULL_PATH}/cadvisor:latest

  node-exporter:
    build:
      context: ./docker/node-exporter/
      cache_from:
        - ${REGISTRY_FULL_PATH}/node-exporter:latest

  alertmanager:
    build:
      context: ./docker/alertmanager/
      cache_from:
        - ${REGISTRY_FULL_PATH}/alertmanager:latest
