version: '3.6'

volumes:
  grafana_data: {}
  prometheus_data: {}

networks:
  frontend:
  backend:

services:
  grafana:
    build: ./docker/grafana/
    restart: always
    networks:
    - frontend
    - backend
    depends_on:
    - prometheus
    volumes:
    - grafana_data:/var/lib/grafana
    - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
    - ./docker/grafana/config.monitoring
    ports:
    - 3000:3000

  prometheus:
    build: ./docker/prometheus/
    restart: always
    depends_on:
      - cadvisor
    networks:
      - backend
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  cadvisor:
    container_name: cadvisor
    build: ./docker/cadvisor/
    restart: always
    networks:
    - backend
    volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /var/run:/var/run:rw
    - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    container_name: node-exporter
    build: ./docker/node-exporter/
    restart: always
    networks:
      - backend
    volumes:
      - /:/rootfs:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  alertmanager:
    container_name: alertmanager
    build: ./docker/alertmanager/
    restart: always
    networks:
      - backend
    volumes:
    - ./docker/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
