version: '3.6'

services:
  grafana:
    ports:
    - 3000:3000

  prometheus:
    ports:
    - 9090:9090

  cadvisor:
    ports:
    - 8080:8080

  node-exporter:
    ports:
    - 9100:9100

  alertmanager:
    ports:
    - 9093:9093
