---

- import_tasks: check_required_vars.yml

- name: "Create {{ commit_sha_dir_path }}/"
  file:
    path: "{{ commit_sha_dir_path }}"
    recurse: yes
    state: directory

- import_tasks: initialize_configuration.yml

- name: "Copy docker-compose files to {{ commit_sha_dir_path }}/"
  copy:
    src: "{{ item }}"
    dest: "{{ commit_sha_dir_path }}"
  loop:
  - ./base.yml
  - ./config.yml
  - ./production.yml
  - ./config.production.yml
  - ./networks.production.yml

- name: Re/start stack
  environment: "{{ docker_compose }}"
  command: >
    docker-compose
      --project-name "{{ project_name }}"
      --file "{{ commit_sha_dir_path }}/base.yml"
      --file "{{ commit_sha_dir_path }}/config.yml"
      --file "{{ commit_sha_dir_path }}/production.yml"
      --file "{{ commit_sha_dir_path }}/config.production.yml"
      --file "{{ commit_sha_dir_path }}/networks.production.yml"
      up
      --detach
      --force-recreate
