---

root_dir_path: "~/apps"
project_dir_path: "{{ root_dir_path }}/{{ project_name }}"
commit_sha_dir_path: "{{ project_dir_path }}/{{ commit_sha }}"
config_dir_path: "{{ commit_sha_dir_path }}/{{ config_dir_name }}"

docker_compose:
  CONFIG_DIR_NAME: "{{ config_dir_name }}"
  REGISTRY_FULL_PATH: "{{ registry_full_path }}"
  IMAGE_TAG: "{{ commit_sha }}"
