apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  version: 1
  editable: false
  orgId: 1
  isDefault: true
  url: http://prometheus:9090
  access: proxy
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: foobar
  # <string> database name, if used
  database:
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."

deleteDatasources:
- name: Prometheus
  orgId: 1
