global:
  scrape_interval:     10s
  scrape_timeout:      10s
  evaluation_interval: 10s
  external_labels:
    monitor: "monitorio"

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["localhost:9090"]

- job_name: "cadvisor"
  dns_sd_configs:
  - names:
    - "cadvisor"
    type: "A"
    port: 8080

- job_name: "node-exporter"
  dns_sd_configs:
  - names:
    - "node-exporter"
    type: "A"
    port: 9100

rule_files:
- "alert.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
